version: '3'

volumes:
  belezana_web_db:

networks:
  localdev:
    name: localdev

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - belezana_web_db:/data/db
    networks:
      - localdev

  belezana_web-api:
    build: backend/
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - belezana_web_db
    networks:
      - localdev
