version: '3'

volumes:
  mssql:

networks:
  localdev:
    name: localdev

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=SenhaBelezanaWeb1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql/data

  belezana_web-api:
    build: backend/
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mssql
    networks:
      - localdev
